name       : kcalutils
version    : 17.04.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/kcalutils-17.04.1.tar.xz : 382228f6f6ee424130d7868d3b77d93be823b33946d4ee090da7f34dd61cf8f6
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kcalcore-devel
    - kcodecs-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
