name       : kcalutils
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kcalutils-17.08.1.tar.xz : f400d0e1b564b950325b95273c655cdd091ea0ff091541ae28a3842e362dd612
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides a set of utility functions that help applications
    access and use calendar data via the KCalCore library.
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kcalcore-devel
    - kcodecs-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
