name       : kcalutils
version    : 21.04.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/kcalutils-21.04.3.tar.xz : 97f94d7e4ad428d05f07a9a6e89eb1e6278fc369d5c0947bcfb0f67f0f451be2
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - grantlee-devel
    - kcalendarcore-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
