name       : kcalutils
version    : 18.04.2
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kcalutils-18.04.2.tar.xz : 62aac71db531ea28e06848c0ab50ac985d82921235f0a1c045e8128b4eff6bfc
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kcalcore-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
