name       : kcalutils
version    : 22.04.2
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/kcalutils-22.04.2.tar.xz : 7bc63dc9bc56bf9f24a025d714227dbd1babe02e9bc280190b6219b3c524d640
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - grantlee-devel
    - kcalendarcore-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
