name       : kcalutils
version    : 21.04.1
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kcalutils-21.04.1.tar.xz : 2cd64365c620d7ca83d9c6a1488da8641d4cc2b97987eb09d7482130d8109b90
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - grantlee-devel
    - kcalendarcore-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
