name       : kcalutils
version    : 21.08.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kcalutils-21.08.0.tar.xz : 3170d850f7586f8b8f8d3f375c79ce70858cea8c000429a6202e1dca68dbe8f9
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - grantlee-devel
    - kcalendarcore-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
