name       : kcalutils
version    : 18.04.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/kcalutils-18.04.1.tar.xz : b5b2b99700899d4075c670aa294818a916dc989e9f5a7385c116790a9c29aa16
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kcalcore-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
