name       : kcalutils
version    : 17.08.2
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kcalutils-17.08.2.tar.xz : 5abf42b7effd295ddfe84b8ef6e8c642105fbe472f4929d2337b064241dec509
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kcalcore-devel
    - kcodecs-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
