name       : kcalutils
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kcalutils-17.08.3.tar.xz : b87d314ac692d07d24149d57ca58f599837fc236e8cfb3f88901e830b6c546ef
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kcalcore-devel
    - kcodecs-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
