name       : kcalutils
version    : 23.04.2
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kcalutils-23.04.2.tar.xz : 09533df6deeaa7c69698a80c7626bf165b998b57791eb7327b179b8ddf3678dd
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - grantlee-devel
    - kcalendarcore-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
