name       : kcalutils
version    : 20.04.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/kcalutils-20.04.2.tar.xz : c5ebbb49f7caf16f613bf0c41191caaf04757b648ce7fa3f93bc08882e9d4315
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kcalendarcore-devel
    - kcodecs-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
