name       : kcalutils
version    : 17.04.0
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/kcalutils-17.04.0.tar.xz : 904933cdbad929e5db8b394bc1c7fc8366de275d80d56319568620955062c445
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kcalcore-devel
    - kcodecs-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
