name       : kcalutils
version    : 21.12.3
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kcalutils-21.12.3.tar.xz : 9a35191c4424ed195e697a0601b1e449654b740cd6d72aa85fa845ffe574da00
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - grantlee-devel
    - kcalendarcore-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
