name       : kcalutils
version    : 17.12.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kcalutils-17.12.3.tar.xz : ab671117c21a42e94d74c946fae99796e96baec978d2bb6b3f1c359cde3d4fb1
license    : LGPL-2.1
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - grantlee-devel
    - kcalcore-devel
    - kcodecs-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - kwidgetsaddons-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
