name       : kcalutils
version    : 22.04.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kcalutils-22.04.0.tar.xz : 478237de88282aa074ff6d83d7af7b8e0e9f24e6bad2c1709215455f09abc972
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library
description: |
    This library provides a set of utility functions that help applications access and use calendar data via the KCalCore library.
builddeps  :
    - grantlee-devel
    - kcalendarcore-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kpimtextedit-devel
    - libical-devel
setup      : |
    %patch -p1 -i $pkgfiles/fix-path.patch 
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
